import type { AskResult, Document } from "./types";

export const demoVideos: Document[] = [
  {
    id: "demo-1",
    url: "pdf://demo-reranker",
    title: "RAG 系统设计指南",
    author: "PDF 文档",
    collection: "AI / RAG",
    summary: "向量检索适合快速召回，Reranker 通过更精细的相关性计算减少无关上下文。",
    transcript: "RAG 的第一阶段通常使用向量检索快速召回候选文本。Reranker 会重新计算相关性。",
    duration: 0,
    status: "ready",
    created_at: new Date().toISOString(),
    source_type: "pdf",
    file_name: "RAG系统设计指南.pdf",
    page_count: 24,
  },
  {
    id: "demo-2",
    url: "pdf://demo-evaluation",
    title: "AI 产品评估手册",
    author: "PDF 文档",
    collection: "AI 产品经理",
    summary: "从检索命中、引用准确、回答相关与来源覆盖四个维度评估 RAG。",
    transcript: "评估 RAG 不能只看最终回答。首先看检索命中率，然后看引用准确率。",
    duration: 0,
    status: "ready",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    source_type: "pdf",
    file_name: "AI产品评估手册.pdf",
    page_count: 36,
  },
  {
    id: "demo-3",
    url: "pdf://demo-agent",
    title: "Agent 产品设计报告",
    author: "PDF 文档",
    collection: "AI 产品经理",
    summary: "从任务边界、用户控制和失败恢复理解 Agent 产品设计。",
    transcript: "Agent 的价值不在于无限自主，而在于明确任务边界并让用户保持控制。",
    duration: 0,
    status: "ready",
    created_at: new Date(Date.now() - 172800000).toISOString(),
    source_type: "pdf",
    file_name: "Agent产品设计报告.pdf",
    page_count: 18,
  },
];

export const demoAnswer: AskResult = {
  answer: "Reranker 位于向量召回之后，会对候选片段进行更精细的相关性排序。它解决了“语义相似但不真正回答问题”的情况，减少送入大模型的无关上下文，从而提高回答准确率和引用质量。",
  grounded: true,
  confidence: 0.91,
  citations: [
    {
      document_id: "demo-1",
      title: "RAG 系统设计指南",
      author: "PDF 文档",
      url: "pdf://demo-reranker",
      start: 0,
      end: 0,
      quote: "Reranker 会把问题和候选文档一起输入交叉编码器，重新计算相关性，再把最可靠的几个片段交给大模型。",
      score: 0.94,
      source_type: "pdf",
      file_name: "RAG系统设计指南.pdf",
      page_number: 12,
    },
    {
      document_id: "demo-2",
      title: "AI 产品评估手册",
      author: "PDF 文档",
      url: "pdf://demo-evaluation",
      start: 0,
      end: 0,
      quote: "引用准确率用来确认检索到的片段是否真的支持最终回答。",
      score: 0.83,
      source_type: "pdf",
      file_name: "AI产品评估手册.pdf",
      page_number: 18,
    },
  ],
};
